<?php $this->context->layout = '@module/page/views/layouts/main2.phtml'?>

<?php
$this->title = tt('Have completed registration', '已完成注册');
?>

<?php
    $this->params['breadcrumbs'] = [
        $this->title
    ]
?>

<style type="text/css">
.email-confirmed-container {
    width: 400px;
    background: #fff;
    padding: 15px;
    border: solid 1px #e0e0e0;
    border-radius: 4px;
}
#btn-login-to-email {
    height: 48px;
    line-height: 40px;
    margin-bottom: 10px;
}
.email-confirmed-container .bg-success {
    font-size: 24px;
    color: #777;
}
.email-confirmed-container .bg-success .iconfont {
    font-size: 28px;
    color: #999;
}
<?php if (isset($_GET['from']) && $_GET['from'] === 'app'):?>
#main-nav .btn-link-rtn{display:none;}
<?php endif?>
</style>

<div class="container email-confirmed-container">
    <p class="notice bg-success" style="line-height:24px;padding:15px;margin-bottom:25px;">
        <span class="iconfont icon-ok-sign"></span>
        <?php _tt('You have completed the registration, Please:', '您已经完成了注册，请：')?>
    </p>
    <?php if (isset($_GET['from']) && $_GET['from'] === 'app'):?>
        <div style="padding-left: 15px;
    color: #999;
    font-size: 18px;
    margin-top: -20px;"><?php _tt('Close this page and return to App and login.', '关闭该页面返回到应用再登陆!')?></div>
    <?php else:?>
        <a href="/login/" class="btn" id="btn-login-to-email"><?php echo _tt('Log In', '登陆')?></a>
    <?php endif?>
</div>
