<?php $this->context->layout = '@module/page/views/layouts/main2.phtml'?>

<?php
$t = \WS::lang('account', true);

$this->title = tt('Email Verify', '邮箱验证');

$this->params['breadcrumbs'] = [
    $this->title
];
$_messages = [
    'en-US'=>[
        '<div class="line"><b>Confirmation email has been sent to "<span id="email-address">{email}</span>", Please click the link in that email to active your account. If you have not received it within 10 mins:</b></div>',
        '<div class="line">1. Please check your spam filters and ensure the emails from our domain are not blocked.</div>',
        '<div class="line">2. You can also try to login with your email/password and click the Resend Email button under My Account</div>'
    ],
    'zh-CN'=>[
        '<div class="line"><b>请您先登陆<span id="email-address">{email}</span>邮箱并激活, 如果无法激活或者没有收到邮件, 请尝试通过以下方法解决:</b></div>',
        '<div class="line">(1) 检查您的邮件信箱中的垃圾箱或广告箱, 邮件可能被误认为垃圾或广告邮件.</div>',
        '<div class="line">(2) 使用您的注册的Email和Password直接进行登陆, 网站将提示"您的用户尚未激活", 请点击"重发激活邮件", 网站将立即再次发送激活邮件.</div>'
    ]
];
$_langName = in_array(\Yii::$app->language, ['en-US', 'zh-CN']) ? \Yii::$app->language : 'en-US';
$_messages = $_messages[$_langName];

$accountNoActiveMessage = tt("Your account hasn't been activated!", '您的帐户尚未激活！');
$accountActivedMessage = tt('Congratulations! Your account has been created successfully!', '恭喜您! 您的帐户已成功创建！');
?>

<style type="text/css">
.email-verify-container {
    background: #fff;
    border: solid 1px #e0e0e0;
    padding: 20px;
    width: 540px;
    border-radius: 4px;
}
.email-verify-container > h3{
    color:#99bd2a;margin-bottom:25px;font-size:20px;
}
#btn-login-to-email {
    height: 48px;
    line-height: 38px;
    margin-top: 50px;
    margin-bottom: 10px;
}
#btn-login-to-email:focus {
    color:#fff;
}
#btn-send-email {
    height: 48px;
    line-height: 38px;
    margin-top: 50px;
    margin-bottom: 0;
}
</style>

<div class="container email-verify-container">
    <h3><?php echo \Yii::$app->request->get('from', '')==='login' 
        ? $accountNoActiveMessage : 
          $accountActivedMessage?></h3>

    <p class="notice" style="line-height:24px;">
        <div style="margin-bottom:15px;"><?php echo str_replace('{email}', $account->email, $_messages[0])?></div>
        <?php echo $_messages[1]?><br/>
        <?php echo $_messages[2]?>
    </p>
    <?php if(\Yii::$app->request->get('from', '')==='login'):?>
        <a href="javascript:void(0)" class="btn" id="btn-send-email" target="_blank" style="margin-right:15px"><?php _tt('Resend confirmation email', '重新发送确认邮件')?></a>
        <a href="javascript:void(0)" class="btn" id="btn-login-to-email" target="_blank" style="margin-top:15px"><?php _tt('Login your email', '登陆邮箱')?></a>
    <?php else:?>
        <a href="javascript:void(0)" class="btn" id="btn-login-to-email" target="_blank"><?php _tt('Login your email', '登陆邮箱')?></a>
    <?php endif?>
</div>

<script>
    $('#btn-login-to-email').click(function(){
        var self = $(this),
            emailHash={ 
                'qq.com': 'http://mail.qq.com', 
                'gmail.com': 'http://mail.google.com', 
                'sina.com': 'http://mail.sina.com.cn', 
                '163.com': 'http://mail.163.com', 
                '126.com': 'http://mail.126.com', 
                'yeah.net': 'http://www.yeah.net/', 
                'sohu.com': 'http://mail.sohu.com/', 
                'tom.com': 'http://mail.tom.com/', 
                'sogou.com': 'http://mail.sogou.com/', 
                '139.com': 'http://mail.10086.cn/', 
                'hotmail.com': 'http://www.hotmail.com', 
                'live.com': 'http://login.live.com/', 
                'live.cn': 'http://login.live.cn/', 
                'live.com.cn': 'http://login.live.com.cn', 
                '189.com': 'http://webmail16.189.cn/webmail/', 
                'yahoo.com.cn': 'http://mail.cn.yahoo.com/', 
                'yahoo.cn': 'http://mail.cn.yahoo.com/', 
                'eyou.com': 'http://www.eyou.com/', 
                '21cn.com': 'http://mail.21cn.com/', 
                '188.com': 'http://www.188.com/', 
                'foxmail.coom': 'http://www.foxmail.com' 
            },
            host = $("#email-address").text().split('@')[1];

        if(emailHash.hasOwnProperty(host)) {
            var url = emailHash[host];
            self.attr('href', url);
        }
    });
$('#btn-send-email').click(function() {
    var $self = $(this);
    $self.attr('disabled', true);
    $.get('/send-email/', {id: "<?php echo $account->id?>", token: "<?php echo $account->access_token?>"}, function(){
        alert('It\'s sent!');
        $self.attr('disabled', false);
    });
    return false;
});
</script>