<?php $this->context->layout = '@module/page/views/layouts/main2.phtml'?>

<?php
$t = \WS::lang('account');

$this->title = $t('Forgot Password Success', [], true);
?>


<?php
    $this->params['breadcrumbs'] = [
        $t('Sent Password to Your Password', [], true)
    ]
?>

<div class="container">
    <div class="bg-success" style="padding:10px">
        <?php if($account):?>
            <span class="glyphicon glyphicon-ok-sign"></span><?php $t('If there is an account associated with {email} you will receive an email with a link to reset your password.', ['email'=>$account->email])?>
        <?php else:?>
            <?php echo $t('Specify the wrong parameters.')?>
        <?php endif?>
    </div>
</div>