<?php $this->context->layout = '@module/page/views/layouts/main2.phtml'?>

<?php
$this->title = tt('Forgot Password Success', '找回密码成功');
?>


<?php
    $this->params['breadcrumbs'] = [
        tt('Sent Password to Your Password', '找回密码已发送')
    ];
    $content = tt('If there is an account associated with %s you will receive an email with a link to reset your password.', 
        '已发送一封电子邮件到您的邮箱%s，请通过点击电子邮件中的链接重置密码!');
?>

<div class="container">
    <div class="bg-success" style="padding:10px;background:#fff;border:solid 1px #ddd;border-radius:3px;">
        <?php if($account):?>
            <span class="glyphicon glyphicon-ok-sign"></span>
                <?php echo sprintf($content, $account->email)?>
        <?php else:?>
            <?php echo tt('Specify the wrong parameters.', '错误的参数指定!')?>
        <?php endif?>
    </div>
</div>