<?php $this->context->layout = '@module/page/views/layouts/main2.phtml'?>

<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$t = \WS::lang('account', true);

$this->title = tt('Forgot Password', '重置密码');
$this->params['breadcrumbs'] = [$this->title]
?>

<div class="forgot-pwd-box">
    <h1><?php echo $t('RETRIEVE YOUR PASSWORD HERE')?></h1>
    <p style="margin-bottom:15px;">
        <?php echo $t('Please enter your email address below. You will receive a link to reset your password.')?>
    </p>
     <?php $form = ActiveForm::begin(['id' => 'forgot-password-form'])?>

        <div class="form-group">
            <?php echo $form->field($formModel, 'email')->textInput([
                'placeholder' => $formModel->getAttributeLabel('email')
            ]) ?>
        </div>
        
        <div class="container-fluid">
            <div class="row">
                <button type="submit" class="btn"><?php _tt('Reset a Password', '重置密码')?></button>
            </div>
        </div>
    <?php ActiveForm::end()?>
</div>