<?php $this->context->layout = '@module/page/views/layouts/main2.phtml'?>

<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = tt('Customer Login', '登陆');
$this->params['breadcrumbs'] = [$this->title]
?>

<div class="login-container">
    <div class="login-box">
        <h1><?php _tt('Login', '登陆')?></h1>
        <a href="/register/" class="btn-register link-btn"><?php _tt('Register now!', '没有帐号? 立即注册')?></a>

        <?php $form = ActiveForm::begin([
            'id' => 'login-form',
            'options' => [
                'class'=>'white-pink'
            ]
        ])?>
            <div class="form-group">
                <?php echo $form->field($formModel, 'account_id')->textInput([
                    'placeholder' => $formModel->getAttributeLabel('account_id')
                ]) ?>
            </div>
            <div class="form-group">
                <?php echo $form->field($formModel, 'password')->passwordInput([
                    'placeholder' => $formModel->getAttributeLabel('password')
                ]) ?>
            </div>
            <div class="form-group mt20">
                <?= $form->field($formModel, 'rememberMe')->checkbox() ?>
                <a href="/forgot-password/" class="btn-forgot-pwd link-btn"><?php _tt('Forget password?', '忘记密码?')?></a>
            </div>
            <div class="form-group mt20">
                <button id="btn-login" class="basisyle btn" type="submit"><?php _tt('Login', '登陆')?></button>
            </div>
        <?php ActiveForm::end()?>
        <!--
        <div class="social-login">
            <h1><span><?php _tt('Wechat login', '社交帐号直接登陆')?></span></h1>
            <a id="btn-wechat" class="link-icon-btn" href="#"><i class="iconfont icon-wechat"></i></a>
        </div>
        -->
    </div>
</div>

<script src="http://res.wx.qq.com/connect/zh_CN/htmledition/js/wxLogin.js"></script>
<script type="text/javascript">
<?php
    $app = \Yii::$app;
?>
$('#btn-wechat').click(function () {
    var obj = new WxLogin({
      id:"login_container", 
      appid: "<?php echo $app->params['wechat']['appId']?>",
      scope: "snsapi_login",
      redirect_uri: "<?php echo $app->request->hostInfo?>/wechat-login/",
      state: "<?php echo $app->request->csrfToken?>",
      style: "white",
      // href: "" /*样式定制*/
    });
});
</script>