<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = tt('Create account', '创建账户');
?>

<?php echo \module\page\widgets\Nav::widget()?>

<div class="register-box">
    <h1><?php _tt('Create account', '创建帐户')?></h1>
    <a href="/login/" class="btn-login link-btn"><?php _tt('Login now!', '已有帐户？直接登陆')?></a>

    <?php $form = ActiveForm::begin(['id' => 'register-form'])?>
        <div class="form-group">
            <?php echo $form->field($formModel, 'username')->textInput([
                'placeholder' => $formModel->getAttributeLabel('username')
            ]) ?>
        </div>
        <div class="form-group">
            <?php echo $form->field($formModel, 'email')->textInput([
                'placeholder' => $formModel->getAttributeLabel('email')
            ]) ?>
        </div>
        <div class="form-group">
            <?php echo $form->field($formModel, 'password')->passwordInput([
                'placeholder' => $formModel->getAttributeLabel('password')
            ]) ?>
        </div>
        <div class="form-group">
            <?php echo $form->field($formModel, 'confirm_password')->passwordInput([
                'placeholder' => $formModel->getAttributeLabel('confirm_password')
            ]) ?>
        </div>
        <div class="form-group mt15">
            <?= $form->field($formModel, 'accept_agreed')->checkbox() ?>
        </div>

        <div style="text-align:center;">
            <button type="submit" class="btn"><?php _tt('Create Account', '创建帐户')?></button>
        </div>
    <?php ActiveForm::end()?>
</div>