<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = tt('Create account', '创建账户');
?>

<?php echo \module\page\widgets\Nav::widget()?>

<div class="register-box">
    <h1><?php _tt('Create account', '创建帐户')?></h1>
    <a href="/login/" class="btn-login link-btn"><?php _tt('Login now!', '已有帐户？直接登陆')?></a>

    <?php $form = ActiveForm::begin(['id' => 'register-form'])?>
        <div class="form-group">
            <?php echo $form->field($formModel, 'email')->textInput([
                'placeholder' => $formModel->getAttributeLabel('email')
            ]) ?>
        </div>
        <div class="form-group">
            <?php echo $form->field($formModel, 'password')->passwordInput([
                'placeholder' => $formModel->getAttributeLabel('password')
            ]) ?>
        </div>
        <div class="form-group">
            <?php echo $form->field($formModel, 'confirm_password')->passwordInput([
                'placeholder' => $formModel->getAttributeLabel('confirm_password')
            ]) ?>
        </div>

        <div class="form-group mt15">
            <div class="form-group field-registerform-accept_agreed has-success">
            <label>
                <input type="checkbox" id="registerform-accept_agreed" name="RegisterForm[accept_agreed]" value="1" aria-invalid="false""><span style="margin-left:5px"><?php _tt('Accept ', '接受')?></span>
            </label>
            <a class="link-btn" href="/protocol/" target="_blank"><?php _tt('USLEJU policy', '米乐居协议条款')?></a>
        </div>

        <div style="text-align:center;">
            <button type="submit" class="btn"><?php _tt('Create Account', '创建帐户')?></button>
        </div>
    <?php ActiveForm::end()?>
</div>

<?php
$errors = $formModel->getErrors();
if (isset($errors['accept_agreed'])):?>
    <script type="text/javascript">
        window.alert(<?php echo json_encode($errors['accept_agreed'][0])?>);
    </script>
<?php endif?>