<?php $this->context->layout = '@module/page/views/layouts/main2.phtml'?>

<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$this->title = tt('Reset a Password', '重置密码');
?>

<style type="text/css">
.reset-password-container {
    width:320px;
}
.reset-password-box > h3 {
    font-size: 20px;
    margin-bottom: 15px;
    color: #99bd2a;
}
.help-block {
    left:332px;
}
</style>

<div class="container reset-password-container">
    <div class="reset-password-box">
        <h3>重置密码</h3>
        <?php $form = ActiveForm::begin(['id' => 'reset-password-form', 'class'=>'form'])?>

        <div class="form-group">
            <?php echo $form->field($formModel, 'new_password')->passwordInput([
                'placeholder' => $formModel->getAttributeLabel('new_password')
            ]) ?>
        </div>
        <div class="form-group">
            <?php echo $form->field($formModel, 'confirm_new_password')->passwordInput([
                'placeholder' => $formModel->getAttributeLabel('confirm_new_password')
            ]) ?>
        </div>

        <div style="margin-top:20px;">
            <button type="submit" class="btn" style="padding:2px 25px;margin-top:5px"><?php _tt('Reset a Password', '重置密码')?></button>
        </div>
    <?php ActiveForm::end()?>
    </div>
</div>

<style>
#reset-password-form .form-control{width:320px;}
</style>