<?php $this->context->layout = '@module/page/views/layouts/main2.phtml'?>

<?php 
use yii\helpers\Html;
use yii\widgets\ActiveForm;

$t = \WS::lang('account');

$this->title = $t('Reset a Password', [], true);
?>

<?php
    $this->params['breadcrumbs'] = [
        $this->title
    ]
?>

<div class="container">
    <div class="reset-password-box">
        <?php $form = ActiveForm::begin(['id' => 'reset-password-form', 'class'=>'form'])?>

        <div class="form-group">
            <?php echo $form->field($formModel, 'new_password')->passwordInput() ?>
        </div>
        <div class="form-group">
            <?php echo $form->field($formModel, 'confirm_new_password')->passwordInput() ?>
        </div>

        <div style="margin-top:20px;">
            <button type="submit" class="btn" style="padding:2px 25px"><?php $t('Reset a Password')?></button>
        </div>
    <?php ActiveForm::end()?>
    </div>
</div>

<style>
#reset-password-form .form-control{width:320px;}
</style>